#!/bin/sh
#PBS -N picmcc
#PBS -q slim
#PBS -l nodes=1:ppn=4,walltime=05:00:00:00
#PBS -V
#PBS -S /bin/bash
#PBS -j oe
#PBS -o ./out.log

# Current path and executable
EXEPATH=$PBS_O_WORKDIR
EXEC="$EXEPATH/launch_pic.py"

cd $EXEPATH

# Nodes and cores
NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | sort | uniq | tee ./nodes.txt | wc -l`
cat $PBS_NODEFILE > ./nodefile.txt

# launch
python $EXEC ./nodefile.txt $EXEPATH
